POST http://localhost:3000/confirmation
Content-Type: application/json

{
    "to": "rohan.jagannathan@utexas.edu"
}

###
POST http://localhost:3000/welcome
Content-Type: application/json

{
    "to": "abhinav.chadaga@utexas.edu"
}
